import "./globals.css";
import type { Metadata } from "next";
import { DarkModeToggle } from "@/components/ui/DarkModeToggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-sans">
        <div style={{ position: "fixed", top: 16, right: 16, zIndex: 50 }}>
          <DarkModeToggle />
        </div>
        {children}
      </body>
    </html>
  );
}
